.oh-my-zsh:
    type: archive
    url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
    exact: true
    stripComponents: 1
    refreshPeriod: 168h
    exclude:
      - "*/cache/**"
.oh-my-zsh/custom/themes/powerlevel10k:
    type: archive
    url: https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz
    stripComponents: 1
    refreshPeriod: 168h
.config/kak/colors/dracula.kak:
    type: file
    url: https://raw.githubusercontent.com/dracula/kakoune/master/colors/dracula.kak
    refreshPeriod: 168h
