colorscheme dracula

set global tabstop 2
set global indentwidth 2

add-highlighter global/ number-lines -relative

# plug.kak (https://github.com/andreyorst/plug.kak)
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "andreyorst/powerline.kak" defer powerline_tomorrow-night %{
        powerline-theme tomorrow-night
} config %{
        powerline-start
}

plug "alexherbo2/auto-pairs.kak"

