colorscheme dracula

set-option global tabstop 4
set-option global indentwidth 4

set-option global scrolloff 1,3

add-highlighter global/ regex \h+$ 0:Error

add-highlighter global/ wrap -word -indent

define-command -docstring "save and quit" x "write-all; quit"

hook global BufCreate .* %[
	add-highlighter buffer/ number-lines -relative -hlcursor
	add-highlighter buffer/ wrap
]

add-highlighter global/ show-matching

# plug.kak (https://github.com/andreyorst/plug.kak)
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "andreyorst/powerline.kak" defer powerline_tomorrow-night %{
    powerline-theme tomorrow-night
} config %{
    powerline-start
}

plug "alexherbo2/auto-pairs.kak"

# Use editorconfig
hook global WinCreate ^[^*]+$ %{editorconfig-load}

hook global WinSetOption filetype=python %{
	set-option window formatcmd 'black -q  -'
}

